name: Metrics
on:
  schedule: [{cron: "27 8 * * 0"}]
  push: {branches: "master"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base_hireable: true
          config_timezone: America/Chicago

          plugin_followup: yes
          plugin_followup_indepth: yes

          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: count # percentage

          plugin_repositories: yes
          plugin_repositories_forks: yes
          plugin_repositories_pinned: 2
          plugin_repositories_starred: 5

          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_days: 180

          # plugin_stargazers: yes
          # plugin_stargazers_charts: no
          # plugin_stargazers_worldmap: yes
          # plugin_stargazers_worldmap_token: ${{ secrets.GOOGLE_MAP_TOKEN }}
          # plugin_stargazers_worldmap_sample: 200

          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_filter: stars:>50
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes

          plugin_achievements: yes
          plugin_achievements_display: detailed # compact
          plugin_achievements_threshold: A

          plugins_gists: yes
          plugin_traffic: yes

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 180
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 673826
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_limit: 2
